Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -41,44 +41,44 @@ jobs:
           -e CLOUDINARY_SECRET=${{ secrets.CLOUDINARY_SECRET }} \
           consitech-lms-backend
 
-    - name: Health check
-      run: |
-        docker logs consitech-lms-backend-container-test
-        RETRIES=3
-        until curl --silent --fail http://localhost:8081 || [ $RETRIES -eq 0 ]; do
-          echo "Waiting for container..."
-          sleep 10
-          RETRIES=$((RETRIES - 1))
-        done
-        if [ $RETRIES -eq 0 ]; then
-          echo "New container failed to start"
-          docker logs consitech-lms-backend-container-test
-          docker rm -f consitech-lms-backend-container-test
-          exit 1
-        fi
+    # - name: Health check
+    #   run: |
+    #     docker logs consitech-lms-backend-container-test
+    #     RETRIES=3
+    #     until curl --silent --fail http://localhost:8081 || [ $RETRIES -eq 0 ]; do
+    #       echo "Waiting for container..."
+    #       sleep 10
+    #       RETRIES=$((RETRIES - 1))
+    #     done
+    #     if [ $RETRIES -eq 0 ]; then
+    #       echo "New container failed to start"
+    #       docker logs consitech-lms-backend-container-test
+    #       docker rm -f consitech-lms-backend-container-test
+    #       exit 1
+    #     fi
 
-    - name: Stop and remove old container
-      run: docker rm -f consitech-lms-container-backend || true
+    # - name: Stop and remove old container
+    #   run: docker rm -f consitech-lms-container-backend || true
 
-    - name: Start new container on the original port
-      run: |
-        docker rm -f consitech-lms-backend-container-test
-        docker run -d --name consitech-lms-container-backend \
-          -p 8080:8080 \
-          --network mynetwork \
-          -e SERVER_PORT=${{ secrets.SERVER_PORT }} \
-          -e DB_URL=${{ secrets.DB_URL }} \
-          -e DB_USER=${{ secrets.DB_USER }} \
-          -e DB_PASS=${{ secrets.DB_PASS }} \
-          -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
-          -e SMTP_HOST=${{ secrets.SMTP_HOST }} \
-          -e SMTP_PORT=${{ secrets.SMTP_PORT }} \
-          -e SMTP_USERNAME=${{ secrets.SMTP_USERNAME }} \
-          -e SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }} \
-          -e ADMIN_EMAIL=${{ secrets.ADMIN_EMAIL }} \
-          -e ADMIN_USERNAME=${{ secrets.ADMIN_USERNAME }} \
-          -e ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }} \
-          -e CLOUDINARY_NAME=${{ secrets.CLOUDINARY_NAME }} \
-          -e CLOUDINARY_KEY=${{ secrets.CLOUDINARY_KEY }} \
-          -e CLOUDINARY_SECRET=${{ secrets.CLOUDINARY_SECRET }} \
-          consitech-lms-backend
+    # - name: Start new container on the original port
+    #   run: |
+    #     docker rm -f consitech-lms-backend-container-test
+    #     docker run -d --name consitech-lms-container-backend \
+    #       -p 8080:8080 \
+    #       --network mynetwork \
+    #       -e SERVER_PORT=${{ secrets.SERVER_PORT }} \
+    #       -e DB_URL=${{ secrets.DB_URL }} \
+    #       -e DB_USER=${{ secrets.DB_USER }} \
+    #       -e DB_PASS=${{ secrets.DB_PASS }} \
+    #       -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
+    #       -e SMTP_HOST=${{ secrets.SMTP_HOST }} \
+    #       -e SMTP_PORT=${{ secrets.SMTP_PORT }} \
+    #       -e SMTP_USERNAME=${{ secrets.SMTP_USERNAME }} \
+    #       -e SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }} \
+    #       -e ADMIN_EMAIL=${{ secrets.ADMIN_EMAIL }} \
+    #       -e ADMIN_USERNAME=${{ secrets.ADMIN_USERNAME }} \
+    #       -e ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }} \
+    #       -e CLOUDINARY_NAME=${{ secrets.CLOUDINARY_NAME }} \
+    #       -e CLOUDINARY_KEY=${{ secrets.CLOUDINARY_KEY }} \
+    #       -e CLOUDINARY_SECRET=${{ secrets.CLOUDINARY_SECRET }} \
+    #       consitech-lms-backend
